# Generated by Django 5.2.16 on 2026-07-31 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'cpf'], name='clients_cli_user_id_74cabd_idx'), models.Index(fields=['user', 'email'], name='clients_cli_user_id_97743a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'email'), name='clients_client_user_email_uniq'), models.UniqueConstraint(condition=models.Q(('cpf__isnull', False)), fields=('user', 'cpf'), name='clients_client_user_cpf_uniq')],
            },
        ),
    ]
