# Generated by Django 5.2.16 on 2026-07-31 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('function', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.BooleanField(default=True)),
                ('mon_times', models.JSONField(blank=True, default=list)),
                ('tue_times', models.JSONField(blank=True, default=list)),
                ('wed_times', models.JSONField(blank=True, default=list)),
                ('thu_times', models.JSONField(blank=True, default=list)),
                ('fri_times', models.JSONField(blank=True, default=list)),
                ('sat_times', models.JSONField(blank=True, default=list)),
                ('sun_times', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Preço em centavos')),
                ('duration', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('status', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='catalog.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='catalog.service')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', through='catalog.EmployeeService', to='catalog.service'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['user', 'status'], name='catalog_ser_user_id_6a3fa8_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeservice',
            constraint=models.UniqueConstraint(fields=('employee', 'service'), name='catalog_employeeservice_emp_svc_uniq'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'status'], name='catalog_emp_user_id_660aeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='catalog_employee_user_email_uniq'),
        ),
    ]
